<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="api.tests.test_ack_views.AckCountViewTestCase-20250630235714" tests="5" file="api/tests/test_ack_views.py" time="0.304" timestamp="2025-06-30T23:57:14" failures="0" errors="1" skipped="0">
	<testcase classname="api.tests.test_ack_views.AckCountViewTestCase" name="test_ackcount_detail" time="0.267" timestamp="2025-06-30T23:57:14" file="advisor/api/tests/test_ack_views.py" line="415"/>
	<testcase classname="api.tests.test_ack_views.AckCountViewTestCase" name="test_ackcount_endpoint_access_fails_for_non_internal_user" time="0.006" timestamp="2025-06-30T23:57:14" file="advisor/api/tests/test_ack_views.py" line="469"/>
	<testcase classname="api.tests.test_ack_views.AckCountViewTestCase" name="test_ackcount_list" time="0.003" timestamp="2025-06-30T23:57:14" file="advisor/api/tests/test_ack_views.py" line="400"/>
	<testcase classname="api.tests.test_ack_views.AckCountViewTestCase" name="test_add_deleting_acks_to_modify_ack_counts" time="0.021" timestamp="2025-06-30T23:57:14" file="advisor/api/tests/test_ack_views.py" line="426"/>
	<testcase classname="api.tests.test_ack_views.AckCountViewTestCase" name="test_ackcount_detail_invalid_rule_id" time="0.007" timestamp="2025-06-30T23:57:14" file="advisor/api/tests/test_ack_views.py" line="452">
		<error type="DoesNotExist" message="Rule matching query does not exist."><![CDATA[Traceback (most recent call last):
  File "/home/pwayper/Code/insights/advisor-backend/api/advisor/api/tests/test_ack_views.py", line 454, in test_ackcount_detail_invalid_rule_id
    response = self.client.get(
               ^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/test/client.py", line 1124, in get
    response = super().get(
               ^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/test/client.py", line 475, in get
    return self.generic(
           ^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/test/client.py", line 671, in generic
    return self.request(**r)
           ^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/test/client.py", line 1087, in request
    self.check_exception(response)
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/test/client.py", line 802, in check_exception
    raise exc_value
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/Code/insights/advisor-backend/api/advisor/api/views/acks.py", line 212, in retrieve
    rule_ack_count = self.queryset.get(rule_id=rule_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwayper/.local/share/virtualenvs/advisor-backend-A3tAKjzl/lib/python3.12/site-packages/django/db/models/query.py", line 633, in get
    raise self.model.DoesNotExist(
api.models.Rule.DoesNotExist: Rule matching query does not exist.
]]></error>
	</testcase>
</testsuite>
