<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20250630235610" tests="1" file="unittest/loader.py" time="0.000" timestamp="2025-06-30T23:56:10" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test" time="0.000" timestamp="2025-06-30T23:56:10" file="/usr/lib64/python3.12/unittest/loader.py" line="32">
		<error type="ImportError" message="Failed to import test module: test
Traceback (most recent call last):
  File &quot;/usr/lib64/python3.12/unittest/loader.py&quot;, line 137, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'api.test'
"><![CDATA[ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/lib64/python3.12/unittest/loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'api.test'

]]></error>
	</testcase>
</testsuite>
